stages:
  data_ingestion:
    cmd: python3 src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images

  prepare_base_model:
    cmd: python3 src/cnnClassifier/pipeline/state_02_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/state_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
      - INCLUDE_TOP
      - WEIGHTS
      - CLASSES

    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python3 src/cnnClassifier/pipeline/stage_03_training.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_training.py
      - src/cnnClassifier/components/prepare_callbacks.py
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/prepare_base_model
      - config/config.yaml

    params:
      - EPOCHS
      - BATCH_SIZE
      - IMAGE_SIZE
      - AUGMENTATION


    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python3 src/cnnClassifier/pipeline/state_04_evaluation.py
    deps:
      - src/cnnClassifier/pipeline/state_04_evaluation.py
      - artifacts/training/model.h5
      - artifacts/data_ingestion/Chicken-fecal-images
      - config/config.yaml

    params:
      - IMAGE_SIZE
      - BATCH_SIZE

    metrics:
    - scores.json:
        cache: false